### ISSUE TITLE
Code Execution Issue: Missing File in Repository

### ISSUE THREAD

**Issue by SmartNight-cc** [AtsuMiyai/LoCoOp#4]
Hello, I am very interested in your work. However, I encountered an issue while trying to run the code: 
`No such file or directory: 'xxx/LoCoOp/data/imagenet/classnames.txt'.`  
I would like to know if there is any missing files in the repository. Looking forward to your reply~

**Comment by AtsuMiyai** [comment]
Thanks for @SmartNight-cc  and @JiuqingDong 's report.
I have added the explanation on  classnames.txt in README.md now.
